from typing import List, Optional
from pydantic import BaseModel, Field


# ==========================================
# 1. INPUT DATA SCHEMAS (RAG Retrieval)
# ==========================================

class OfferExtraction(BaseModel):
    title: str = Field(..., description="Target job position title")
    technical_skills: List[str] = Field(default_factory=list, description="Extracted hard technical skills")
    required_experiences: List[str] = Field(default_factory=list, description="Target missions and experience expectations")
    non_technical_skills: List[str] = Field(default_factory=list, description="Soft skills and organizational attributes")
    motivations: List[str] = Field(default_factory=list, description="Company cultural values and candidate motivations")
    keywords: List[str] = Field(default_factory=list, description="High-frequency ATS keywords")


class ExperienceItem(BaseModel):
    company: str
    role: str
    period: str
    location: str
    description: List[str] = Field(default_factory=list, description="Bullet points of tasks and achievements")


class RetrievedExperiences(BaseModel):
    experiences: List[ExperienceItem] = Field(default_factory=list)


class ProjectItem(BaseModel):
    title: str
    technologies: List[str] = Field(default_factory=list)
    description: List[str] = Field(default_factory=list, description="Key features, architecture, and impact")


class RetrievedProjects(BaseModel):
    projects: List[ProjectItem] = Field(default_factory=list)


class RAGGenerationPayload(BaseModel):
    """Container schema mapping directly to your incoming JSON payload."""
    offer_extraction: OfferExtraction
    best_experiences: RetrievedExperiences
    best_projects: RetrievedProjects


# ==========================================
# 2. OUTPUT DATA SCHEMAS (LLM -> LaTeX Engine)
# ==========================================

class CVHeader(BaseModel):
    name: str = Field(..., description="Candidate full name")
    title: str = Field(..., description="Target professional title aligned with the offer")
    city: str = Field(..., description="City and country")
    phone: str = Field(..., description="Phone number")
    email: str = Field(..., description="Contact email")
    linkedin: Optional[str] = Field(None, description="LinkedIn profile URL")
    github: Optional[str] = Field(None, description="GitHub profile URL")


class CVEducation(BaseModel):
    degree: str = Field(..., description="Degree and field of study")
    school: str = Field(..., description="University / Institution name")
    graduation_year: str = Field(..., description="Year or graduation period")
    description: Optional[str] = Field(None, description="Honors, key coursework, or achievements")


class CVExperience(BaseModel):
    company: str
    role: str
    start_date: str = Field(..., description="Start date (e.g., 'Feb 2026')")
    end_date: str = Field(..., description="End date or 'Present'")
    location: str
    bullets: List[str] = Field(
        ...,
        min_length=1,
        max_length=5,
        description="Action-verb-driven bullet points tailored to the job offer"
    )


class CVProject(BaseModel):
    title: str
    technologies: str = Field(..., description="Comma-separated list of technologies (e.g. 'FastAPI, Docker, PostgreSQL')")
    bullets: List[str] = Field(
        ...,
        min_length=1,
        max_length=4,
        description="Key engineering deliverables and results"
    )


class GeneratedCV(BaseModel):
    """Target structured schema generated by the LLM before LaTeX rendering."""
    header: CVHeader
    professional_summary: str = Field(
        ...,
        description="3-4 sentence professional summary aligning candidate strengths with the target role."
    )
    technical_competencies: List[str] = Field(
        ...,
        description="Categorized technical competencies (e.g., 'Languages: Python, SQL', 'Frameworks: FastAPI, Docker')"
    )
    experiences: List[CVExperience] = Field(..., description="Tailored work experiences")
    projects: List[CVProject] = Field(..., description="Tailored portfolio projects")
    education: List[CVEducation] = Field(default_factory=list, description="Candidate education history")
    languages: List[str] = Field(default_factory=list, description="Spoken languages and proficiencies")
    leadership: Optional[str] = Field(None, description="Extracurriculars, hackathons, or soft skill initiatives")